kube: More checks and rules for inspecting
Regression observed with ingress so only v1.15.4 is supported now

Relate-to: https://github.com/rzr/webthing-iotjs/wiki/Kube
Change-Id: I95352ac24ee10915098773ee5dd7e64f20c7cd06
Signed-off-by: Philippe Coval <p.coval@samsung.com>

diff --git a/extra/tools/kube/Makefile b/extra/tools/kube/Makefile
--- a/extra/tools/kube/Makefile
+++ b/extra/tools/kube/Makefile
@@ -5,17 +5,18 @@
 # SPDX-License-Identifier: MIT
 
 default: help
-	@echo "# log: $@: $<"
+	@echo "# log: $@: $^"
 
 
 name?=iotjs-express
-revision?=$(shell git describe --tags || echo "0.0.0")
+revision?=$(shell git describe --tags 2> /dev/null || echo "0.0.0")
 port?=8888
 nodePort?=30080
 type=NodePort
 docker?=docker
 k8s?=microk8s
-kubectl?=${k8s}.kubectl
+k8s_prefix?=${k8s}.
+kubectl?=/snap/bin/${k8s}.kubectl
 topdir?=../../..
 username?=tmp
 image?=${username}/${name}:${revision}
@@ -27,6 +28,9 @@ endpoint?=/
 url?=http://${host}${endpoint}
 sudo?=sudo
 snap?=snap
+PATH:=${PATH}:/snap/bin
+export PATH
+#snap_install_args?=--channel 1.15/stable
 
 
 help:	
@@ -40,7 +44,7 @@ help:
 	@echo "# make client"
 	@echo "### Config: "
 	@echo "# revision=${revision}"
-	@echo "# log: $@: $<"
+	@echo "# log: $@: $^"
 
 setup/debian/%:
 	${sudo} apt-get update
@@ -48,15 +52,36 @@ setup/debian/%:
 	${sudo} ${snap} version
 
 setup/${k8s}:
-	${sudo} ${snap} install ${k8s} --classic
+	${sudo} ${snap} refresh
+	${sudo} ${snap} info ${k8s}
+	${sudo} ${snap} install ${k8s} ${snap_install_args} --classic
+	@echo "# ${sudo} ${snap} remove ${k8s} # To remove"
 
-setup/debian: setup/debian/docker.io setup/debian/snapd
+setup/debian: setup/debian/docker.io /etc/docker/daemon.json \
+  setup/debian/snapd \
+  setup/debian/lsof \
+  setup/debian/time
 	-groups | grep docker \
 	|| echo '# TODO: sudo addgroup ${USER} docker && sudo su -l ${USER}'
-	@echo "# log: $@: $<"
+	@echo "# log: $@: $^"
+
+user:
+	@groups | grep docker || { ${sudo} usermod -a -G docker "${USER}" && echo 'sudo su -l ${USER}' ; }
+	@groups | grep ${k8s} || { ${sudo} usermod -a -G ${k8s} "${USER}" && echo 'sudo su -l ${USER}' ; }
 
 setup: setup/debian setup/${k8s}
-	@echo "# log: $@: $<"
+	@echo "# log: $@: $^"
+
+
+evict:  /var/snap/${k8s}/current/args/kubelet
+	${k8s}.status --wait-ready
+	${kubectl} get all | grep 'Evicted'
+	grep eviction "$<"
+	sudo sed -b -e 's|1Gi|100Mi|g' -i "$<"
+
+restart:
+	${MAKE} stop start
+
 
 ${name}.yml: deployment.yml service.yml Makefile
 	@echo '#YAML' > $@
@@ -67,58 +92,78 @@ ${name}.yml: deployment.yml service.yml Makefile
 	@echo '---'  >> $@
 
 spec: ${name}.yml
-	@echo "# log: $@: $<"
+	@echo "# log: $@: $^"
 
 ${topdir}: Makefile
-	@echo "# log: $@: $<"
+	@echo "# log: $@: $^"
 
 build: ${topdir} Makefile
 	${docker} build --tag "${image}" $<
 
 import: build
+	${k8s}.status --wait-ready
 	${docker} save "${image}" \
- | ${k8s}.ctr -n ${namespace} image import -
-	${k8s}.ctr --namespace ${namespace} image list \
- | grep "${image}"
+ | time ${sudo} ${k8s}.ctr -n ${namespace} image import -
+	${k8s}.status --wait-ready
+
+image:
+	${sudo} ${k8s}.ctr --namespace ${namespace} image list \
+  | grep "${image}" \
+  || ${sudo} ${k8s}.ctr --namespace ${namespace} image list \
+  | grep "${name}"
 
 save: build
 	@mkdir -p ${image}.tmp
 	@rmdir ${image}.tmp
 	time docker save "${image}" > "${image}.tar"
+	${k8s}.status --wait-ready
 	${k8s}.ctr --namespace ${namespace} image import  "${image}.tar"
 	rm "${image}.tar"
+	${k8s}.status --wait-ready
 	${k8s}.ctr --namespace ${namespace} image list | grep "${image}"
 
 deployment.yml: Makefile
+	${k8s}.status --wait-ready
 	${kubectl} create deployment ${name} \
  --image "${image}" \
  --dry-run -o yaml > $@
 
 service.yml: deployment.yml Makefile
+	${k8s}.status --wait-ready
 	${kubectl} apply -f $<
 	${kubectl} expose deployment ${name} \
  --type=${type} --port ${port}  \
  --dry-run -o yaml > $@
 
 apply: ${name}.yml
+	${k8s}.status --wait-ready
 	${kubectl} apply -f $<
 	${kubectl} describe service/${name}
+	${k8s}.status --wait-ready
 
 enable:
+	${k8s}.status --wait-ready
 	@echo "TODO check if :80 is used"
 	-@${sudo} lsof -i :80
 	${k8s}.enable dns
+	${k8s}.status --wait-ready
 	-${k8s}.disable ingress
+	${k8s}.status --wait-ready
 	${k8s}.enable ingress
+	${k8s}.status --wait-ready
+	${k8s}.status | grep 'ingress: enabled' || ${k8s}.status | grep "ingress: " || sleep 10
 	${k8s}.status | grep 'ingress: enabled'
-	-${kubectl} get ing | grep ${name}
 
-ingress: ingress.yml enable
+ingress: ingress.yml # enable
+	${k8s}.status --wait-ready
 	-${kubectl} delete ingress.extensions/${name}
 	sed -e "s|host: .*|host: ${host}|g" < $< | ${kubectl} apply -f -
+	${k8s}.status --wait-ready
 	${kubectl} get ingress.extensions/${name}
-	${kubectl} describe ingress.extensions/${name} | grep "Address:"
+	${kubectl} describe ingress.extensions/${name} | grep "Address: "
 	${kubectl} get ing
+	${MAKE} log/nginx-ingress
+	@echo "# log: Wait Ready Status ($@)"
 
 client:
 	-ping -c 1 ${host}
@@ -129,21 +174,41 @@ client/test:
 	-curl -kLi ${url}.well-known/security.txt
 	-curl -kLi ${url}favicon.ico
 
+inspect: 
+	-sudo mv -v \
+/var/snap/${k8s}/current/inspection-report \
+/var/snap/${k8s}/current/inspection-report._$(shell date -u +"%Y%m%d_%s").bak
+	${sudo} ${k8s}.inspect
+
 status:
+	-${k8s}.status 
+	${k8s}.status --wait-ready || ${MAKE} inspect
 	${MAKE} status/all | grep ${name}
+	-${kubectl} get ing | grep ${name}
 	-${kubectl} describe ingress.extensions/${name}
 	-${kubectl} describe ingress.extensions/${name} | grep "Address:" \
- || echo "warning: Address missing in ingress"
-	-${k8s}.ctr --namespace ${namespace} image list | grep "${image}"
+ || echo "warning: Address missing in ingress" \
+ && make log/nginx-ingress
 	-grep "${host}" /etc/hosts
 
 status/all:
+	${k8s}.status --wait-ready
 	-${kubectl} get all
 	-${kubectl} get all --all-namespaces
 	-${kubectl} get ingress.extensions
 
-start: help spec import apply enable ingress
-	@echo "# log: $@: $<"
+${k8s}/start:
+	${k8s}.start
+	${k8s}.status --wait-ready
+
+load: help spec import enable apply ingress
+	@echo "# log: $@: $^"
+
+start: ${k8s}/start load
+	@echo "# log: $@: $^"
+
+stop:
+	${k8s}.stop
 
 run: apply status proxy client
 	@echo "# make status proxy"
@@ -154,7 +219,7 @@ run: apply status proxy client
 demo: delete start
 	${MAKE} run \
  || echo "# log: may be failed, try again: make status run"
-	@echo "# log: $@: $<"
+	@echo "# log: $@: $^"
 
 patch:
 	${kubectl} patch service/${name}  --type='json' \
@@ -172,19 +237,67 @@ host: /etc/hosts
 	ping -c1 ${host} || echo "127.0.0.1 ${host}" | ${sudo} tee -a $<
 	ping -c1 ${host}
 
-delete:
+delete/src:
 	rm -fv deployment.yml service.yml ${name}.yml
+
+delete/run:
 	-${kubectl} delete service/${name}
 	-${kubectl} delete deployment.apps/${name}
 	-${kubectl} delete ingress.extensions/${name}
+	${k8s}.status --wait-ready
 
-log/nginx-ingress:
-	pod=$(shell ${kubectl} get all | grep -o "pod/${@F}-[^ ]*" || echo "pod/TODO/$@") \
+reset: delete
+	${k8s}.status --wait-ready
+	-${k8s}.disable ingress
+	-${k8s}.disable dns
+	-${k8s}.disable registry
+	yes | ${k8s}.reset --destroy-storage
+	${k8s}.status --wait-ready
+
+delete: delete/src delete/run
+	@echo "# log: $@: $^"
+
+log/%:
+	${k8s}.status --wait-ready
+	pod=$(shell ${kubectl} get all | grep -o "pod/${@F}-[^ ]*" || echo "pod/TODO/$@" | head -n 1) \
  && echo "# log: pod=$${pod}" \
  && ${kubectl} describe "$${pod}" \
- && ${kubectl} log -f "$${pod}"
+ && ${kubectl} logs "$${pod}"
+
+log/pod: log/${name}
+	${kubectl} get all --all-namespaces | grep "pod/${name}"
+
+log/nginx-ingress:
+	${kubectl} get all --all-namespaces | grep "pod/${@F}-"
+
+log: log/pod log/nginx-ingress
+	@echo "# log: $@: $^"
+
+/etc/docker/daemon.json:
+	echo '{ "insecure-registries" : ["localhost:32000"] }' | ${sudo} tee -a $<
+
+iptables:
+	${sudo} iptables -P FORWARD ACCEPT
+	${sudo} iptables -L
 
 
-log: log/nginx-ingress
-	@echo "# log: $@: $<"
+uninstall:
+	-${MAKE} delete
+	-${MAKE} reset
+	-${NAKE} stop
+	${sudo} ${snap} remove ${k8s}
+	${sudo} iptables -L
+	@echo "sudo iptables -F # Could help too"
 
+purge: stop ${k8s}/start delete reset stop uninstall backup
+	sync
+
+backup: stop
+	${sudo} mv ${HOME}/.kube ${HOME}/.kube._$(shell date -u +"%Y%m%d_%s").bak
+	${sudo} mv ${HOME}/snap/microk8s ${HOME}/snap/microk8s._$(shell date -u +"%Y%m%d_%s").bak
+	-${sudo} du -hsc /var/snap/microk8s/*
+	-${sudo} mv /var/snap/microk8s /var/snap/microk8s._$(shell date -u +"%Y%m%d_%s").bak
+
+version:
+	snap info ${k8s}
+	cat /proc/cpuinfo
